@extends('layouts.site')
@section('title','Compound Interest Calculator with Monthly Contributions')
@section('description','Estimate savings growth with our free compound interest calculator. Compare monthly contributions, view a yearly breakdown and download your results.')
@section('content')
<div class="wrap calculator-page"><nav class="bread" aria-label="Breadcrumb"><a href="{{ route('home') }}">Home</a> / Savings calculator</nav><header class="info-hero"><span class="eyebrow">FREE FINANCIAL TOOL</span><h1>See what steady saving could build.</h1><p>Explore compound interest with a starting amount and regular monthly contributions. Your numbers stay in your browser.</p></header>
<div class="calculator-grid"><form id="savings-calculator" class="calculator-panel"><h2>Your savings scenario</h2><label>Currency<select name="currency"><option>USD</option><option>PKR</option><option>GBP</option><option>EUR</option><option>INR</option><option>AED</option></select></label><label>Starting balance<input name="principal" type="number" min="0" max="100000000" step="0.01" value="1000" required></label><label>Monthly contribution<input name="monthly" type="number" min="0" max="1000000" step="0.01" value="100" required></label><label>Annual interest rate (%)<input name="rate" type="number" min="0" max="30" step="0.01" value="5" required></label><label>Years to save<input name="years" type="number" min="1" max="50" step="1" value="10" required></label><button class="btn primary" type="submit" disabled>Calculate savings</button><p class="meta">Example inputs are illustrative. Currency changes the display, not exchange rates.</p></form>
<section class="calculator-panel" aria-labelledby="result-title"><h2 id="result-title">Your projected balance</h2><div id="calculator-result" aria-live="polite"></div><div class="savings-bar" aria-hidden="true"><span id="contribution-bar"></span></div><p class="meta">Teal: money contributed &middot; Gold: estimated interest</p><button class="btn ghost" id="download-savings" type="button" hidden>Download yearly breakdown (CSV)</button><div class="calculator-table"><table><caption>Year-by-year projection</caption><thead><tr><th>Year</th><th>Contributed</th><th>Interest</th><th>Balance</th></tr></thead><tbody id="savings-rows"></tbody></table></div><noscript><p>Enable JavaScript to calculate.</p></noscript></section></div>
<section class="prose calculator-explanation"><h2>How this calculator works</h2><p>Interest compounds monthly at your annual rate divided by 12. Contributions are added at the end of each month. Each month's balance equals the previous balance multiplied by (1 + annual rate / 1200), plus the monthly contribution.</p><h2>What is compound interest?</h2><p>Compound interest is growth earned on both your original savings and interest already accumulated.</p><h2>What happens at a zero interest rate?</h2><p>Your ending balance is the starting amount plus all monthly contributions.</p><h2>Does this predict investment returns?</h2><p>No. This is a constant-rate illustration, not a forecast or financial advice. Actual rates and returns can vary or be negative. Taxes, fees, inflation and withdrawals are excluded.</p><p>Learn more with the <a href="https://www.investor.gov/financial-tools-calculators/calculators/compound-interest-calculator" rel="noopener noreferrer">SEC's compound interest calculator</a>, or <a href="{{ route('search',['q'=>'saving']) }}">explore our savings guides</a>.</p></section></div>
<script type="module" src="{{ asset('assets/calculator.js') }}"></script>
@endsection
