"""Frontend-only editorial workspace screens for the static design preview."""
from html import escape
from faq_content import FAQ_GROUPS

NAV = [
    ('Workspace', [('index', 'Overview', 'dashboard'), ('articles', 'Articles', 'article'), ('editor', 'Write article', 'edit'), ('media', 'Media library', 'media')]),
    ('Editorial', [('categories', 'Categories', 'categories'), ('tags', 'Tags', 'tag'), ('authors', 'Authors', 'users'), ('faq', 'FAQs', 'comment'), ('comments', 'Comments', 'comment')]),
    ('Publication', [('seo', 'SEO & discovery', 'search'), ('advertisements', 'Advertising', 'ad'), ('newsletter', 'Newsletter', 'mail'), ('settings', 'Settings', 'settings')]),
]

ICON_PATHS = {
    'dashboard':'<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/>',
    'article':'<path d="M6 3h9l4 4v14H6z"/><path d="M15 3v5h4M9 12h7M9 16h7"/>',
    'edit':'<path d="M4 20h16M6 16l10-10 3 3-10 10-4 1zM15 7l2-2a2 2 0 0 1 3 3l-2 2"/>',
    'media':'<rect x="3" y="4" width="18" height="16" rx="2"/><circle cx="8" cy="9" r="1.5"/><path d="m4 17 5-5 3 3 3-3 5 5"/>',
    'categories':'<path d="M4 6h7l2 2h7v11H4zM4 6V4h7"/>',
    'tag':'<path d="M3 4h10l8 8-9 9-9-9z"/><circle cx="8" cy="9" r="1"/>',
    'users':'<circle cx="9" cy="8" r="3"/><path d="M3 20v-2a6 6 0 0 1 12 0v2zM17 6a3 3 0 0 1 0 6M18 15a5 5 0 0 1 3 5"/>',
    'comment':'<path d="M4 4h16v13H9l-5 4z"/><path d="M8 9h8M8 13h5"/>',
    'search':'<circle cx="10" cy="10" r="6"/><path d="m15 15 6 6M8 10h4"/>',
    'ad':'<rect x="3" y="5" width="18" height="14" rx="2"/><path d="M6 9h12M6 13h8"/>',
    'mail':'<rect x="3" y="5" width="18" height="14" rx="2"/><path d="m4 7 8 6 8-6"/>',
    'settings':'<circle cx="12" cy="12" r="3"/><path d="M10 2h4l1 3 3 1 3-1 2 4-2 2v3l2 2-2 4-3-1-3 1-1 3h-4l-1-3-3-1-3 1-2-4 2-2v-3L1 9l2-4 3 1 3-1z"/>',
}
def icon(name): return '<svg viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'+ICON_PATHS[name]+'</svg>'

DESCRIPTIONS = {
    'index': ('Overview', 'Keep the publication moving, from first draft to final review.'),
    'articles': ('Articles', 'Plan, review, and organize every story in one place.'),
    'editor': ('Write article', 'Build a clear, well-structured finance guide.'),
    'media': ('Media library', 'Manage the images that give each story its identity.'),
    'categories': ('Categories', 'Shape the topics readers use to explore the publication.'),
    'tags': ('Tags', 'Connect related ideas without duplicating categories.'),
    'authors': ('Authors', 'Keep attribution and contributor information accurate.'),
    'comments': ('Comments', 'Review reader contributions before they appear.'),
    'faq': ('FAQs', 'Draft answers to the questions readers ask most often.'),
    'seo': ('SEO & discovery', 'Check how the publication is described and found.'),
    'advertisements': ('Advertising', 'Reserve space without interrupting the reading experience.'),
    'newsletter': ('Newsletter', 'Plan the brief and manage its signup experience.'),
    'settings': ('Settings', 'Manage the publication identity and presentation.'),
}

def link(section): return '/admin/' + section + '.html'
def badge(text, tone='neutral'): return f'<span class="status status-{tone}">{escape(text)}</span>'
def sample_notice(): return '<div class="admin-sample"><span class="sample-dot"></span>Design preview · sample content and figures · changes are not saved</div>'
def field(label, value='', typ='text', hint=''):
    return f'<label class="admin-field"><span>{escape(label)}</span><input type="{typ}" value="{escape(value, quote=True)}" placeholder="{escape(hint, quote=True)}"></label>'
def button(label, cls='secondary', action='demo'): return f'<button class="a-button {cls}" type="button" data-admin-action="{action}">{label}</button>'

def shell(section, content):
    name,desc=DESCRIPTIONS[section]
    groups=''.join(f'<div class="side-group"><div class="side-group-label">{label}</div>'+''.join(f'<a class="side-link {"active" if key==section else ""}" href="{link(key)}" {"aria-current=page" if key==section else ""}><span class="side-icon">{icon(icon_name)}</span><span>{title}</span></a>' for key,title,icon_name in items)+'</div>' for label,items in NAV)
    return f'''<div class="studio">
      <aside class="studio-sidebar"><a class="studio-brand" href="/"><img src="/assets/logo-white.svg" alt="FinancersHub" width="184" height="34"><span>EDITORIAL STUDIO</span></a><nav aria-label="Editorial studio">{groups}</nav><div class="side-bottom"><div class="user-dot">FH</div><div><strong>Editorial team</strong><small>Workspace preview</small></div><span aria-hidden="true">⋯</span></div></aside>
      <div class="studio-workspace"><header class="studio-topbar"><button class="mobile-studio-menu" id="studio-menu" type="button" aria-label="Open studio menu" aria-expanded="false">☰</button><div class="studio-crumb">FinancersHub <span>/</span> Editorial studio <span>/</span> {name}</div><div class="topbar-actions"><button class="studio-theme" id="studio-theme" type="button" aria-label="Toggle studio dark mode">◐</button><a href="/" target="_blank" rel="noopener">View site ↗</a><a class="topbar-create" href="/admin/editor.html">＋ New article</a><span class="topbar-avatar" aria-label="Editorial team">FH</span></div></header>
      <main id="main" class="studio-main">{sample_notice()}<div class="studio-heading"><div><span class="admin-kicker">EDITORIAL STUDIO / {section.upper()}</span><h1>{name}</h1><p>{desc}</p></div></div>{content}</main></div></div>'''

def overview(articles):
    tasks=[('A clearer way to build an emergency fund','In review','Personal Finance','Today','amber'),('How index funds work, in plain English','Draft','Investing','Yesterday','blue'),('What to check before opening a new bank account','Scheduled','Banking','Sep 28','purple')]
    rows=''.join(f'<tr><td><a class="story-title" href="/admin/editor.html">{t}</a><small>Sample story · Editorial team</small></td><td>{cat}</td><td>{badge(status,tone)}</td><td class="muted">{date}</td><td><a class="row-action" href="/admin/editor.html">Open ↗</a></td></tr>' for t,status,cat,date,tone in tasks)
    bars=''.join(f'<div class="chart-col"><div class="chart-bar" style="height:{height}%"></div><span>{day}</span></div>' for day,height in [('Mon',36),('Tue',51),('Wed',44),('Thu',67),('Fri',57),('Sat',79),('Sun',71)])
    activity=''.join(f'<div class="activity-item"><span class="activity-icon" aria-hidden="true">{icon}</span><div><strong>{title}</strong><span>{detail}</span></div><time>{when}</time></div>' for icon,title,detail,when in [('✎','Emergency fund guide','Ready for editorial review','Today'),('▦','Bank account checklist','Scheduled in the sample calendar','Sep 28'),('✉','The Weekly Brief','Newsletter draft in progress','Sep 30')])
    return f'''<div class="admin-metrics"><div><span>Published articles</span><strong>104</strong><small>Illustrative count</small><i>▤</i></div><div><span>In review</span><strong>08</strong><small>Illustrative count</small><i>◷</i></div><div><span>Scheduled</span><strong>06</strong><small>Illustrative count</small><i>▦</i></div><div><span>Drafts</span><strong>18</strong><small>Illustrative count</small><i>✎</i></div></div>
      <div class="admin-two-col dashboard-activity"><section class="studio-panel"><div class="panel-head"><div><span class="admin-kicker">SAMPLE ANALYTICS</span><h2>Reader activity</h2></div><span class="small-muted">Illustrative · 7 days</span></div><div class="chart" role="img" aria-label="Illustrative reader activity bar chart for seven days">{bars}</div><p class="chart-note">Preview values show the intended chart layout. Connect verified analytics before showing live metrics.</p></section><section class="studio-panel activity-panel"><div class="panel-head"><div><span class="admin-kicker">EDITORIAL WORKFLOW</span><h2>Recent activity</h2></div></div>{activity}</section></div>
      <section class="studio-panel attention-panel"><div class="panel-head"><div><span class="admin-kicker">YOUR WORKFLOW</span><h2>Needs attention</h2></div><a href="/admin/articles.html">View all articles ↗</a></div><div class="table-scroll"><table class="studio-table"><thead><tr><th>Article</th><th>Section</th><th>Status</th><th>Updated</th><th></th></tr></thead><tbody>{rows}</tbody></table></div></section>
      <div class="admin-two-col lower"><aside class="studio-panel agenda"><div class="panel-head"><div><span class="admin-kicker">COMING UP</span><h2>Editorial calendar</h2></div></div><div class="agenda-item"><time>28 <small>SEP</small></time><div><strong>Banking checklist</strong><span>Scheduled article · 09:00</span></div></div><div class="agenda-item"><time>30 <small>SEP</small></time><div><strong>Weekly finance brief</strong><span>Newsletter draft · 11:00</span></div></div><div class="agenda-item"><time>02 <small>OCT</small></time><div><strong>Investing review</strong><span>Editorial review · 14:00</span></div></div><a class="quiet-link" href="/admin/articles.html">Open publishing queue ↗</a></aside><section class="studio-panel quick-panel"><div class="panel-head"><div><span class="admin-kicker">SHORTCUTS</span><h2>Manage the publication</h2></div></div><a href="/admin/editor.html"><span>✎</span><strong>Start a new article</strong><b>↗</b></a><a href="/admin/media.html"><span>▧</span><strong>Explore the media library</strong><b>↗</b></a><a href="/admin/advertisements.html"><span>▣</span><strong>Review ad placements</strong><b>↗</b></a></section></div>'''

def article_list(articles):
    states=[('Published','green'),('Draft','blue'),('In review','amber'),('Scheduled','purple')]
    rows=''.join(f'<tr data-row-status="{states[i%4][0].lower().replace(" ","-")}" data-row-search="{escape((a[0]+" "+a[1]).lower(),quote=True)}"><td><label class="check"><input type="checkbox" aria-label="Select {escape(a[0],quote=True)}"></label></td><td><a class="story-title" href="/admin/editor.html">{escape(a[0])}</a><small>/articles/{a[4]}</small></td><td>{a[1]}</td><td>{badge(*states[i%4])}</td><td class="muted">Editorial team</td><td class="muted">Sep {24-i}, 2026</td><td><a class="row-action" href="/admin/editor.html" aria-label="Edit {escape(a[0],quote=True)}">Edit ↗</a></td></tr>' for i,a in enumerate(articles))
    return f'''<div class="list-toolbar"><div class="segmented" role="group" aria-label="Filter articles">{''.join(f'<button type="button" class="{"selected" if k=="all" else ""}" data-status-filter="{k}">{t}</button>' for k,t in [('all','All articles'),('published','Published'),('draft','Drafts'),('in-review','In review'),('scheduled','Scheduled')])}</div><a class="a-button primary" href="/admin/editor.html">＋ New article</a></div><section class="studio-panel list-panel"><div class="table-controls"><label class="table-search">⌕ <input id="admin-search" type="search" placeholder="Search titles or categories" aria-label="Search articles"></label><div><select aria-label="Category filter"><option>All categories</option>{''.join(f'<option>{x}</option>' for x in ['Personal Finance','Investing','Banking','Credit','Business'])}</select>{button('Filters ▾')}</div></div><div class="table-scroll"><table class="studio-table"><thead><tr><th><input type="checkbox" aria-label="Select all visible articles" id="select-all"></th><th>Article</th><th>Category</th><th>Status</th><th>Author</th><th>Last updated</th><th></th></tr></thead><tbody>{rows}</tbody></table></div><div class="table-footer"><span id="article-count">Showing 11 sample articles</span><span>1 of 1 pages</span></div></section>'''

def editor():
    sample='<h2>Start with the decision</h2><p>Explain what the reader is trying to decide, then show the costs, limits, and questions that matter.</p><h2>What to check</h2><ul><li>Use current primary sources.</li><li>Show trade-offs and uncertainties.</li><li>Provide a practical next step.</li></ul>'
    return f'''<div class="editor-status"><div><span class="status status-blue">Draft</span><span id="draft-state">Browser-local draft preview · no CMS connected</span></div><div>{button('Preview','secondary','preview')} {button('Save to this browser','primary','save')} {button('Publish ▾','dark','publish')}</div></div>
      <div class="editing-layout"><div class="editing-main"><div class="studio-panel story-setup"><span class="admin-kicker">THE STORY</span><label class="admin-field"><span>Headline <em>*</em></span><input class="headline-input" id="editor-title" value="A clearer way to build an emergency fund" aria-label="Article headline"></label><label class="admin-field"><span>Short description</span><textarea id="editor-summary" rows="2">A practical framework for choosing a target, setting a pace, and keeping cash available when you need it.</textarea><small>A concise summary for listings and search results.</small></label></div>
      <section class="studio-panel editor-panel"><div class="editor-panel-top"><span class="admin-kicker">ARTICLE BODY</span><span id="editor-mode">TinyMCE setup</span></div><div class="tinymce-setup" id="tinymce-setup"><div><strong>Write with TinyMCE</strong><p>Enter your Tiny Cloud API key to activate the visual editor. The key is kept in this browser for this preview. Add this Site’s domain to your approved domains in Tiny Cloud.</p></div><label class="sr-only" for="tinymce-key">Tiny Cloud API key</label><div class="tinymce-key-row"><input id="tinymce-key" type="password" autocomplete="off" placeholder="Your Tiny Cloud API key"><button class="a-button primary" id="activate-tinymce" type="button">Activate editor</button><button class="a-button secondary" id="forget-tinymce-key" type="button">Forget key</button></div><p id="tinymce-status" role="status">No API key is configured. You can still edit the HTML below.</p></div><label class="sr-only" for="article-body">Article body HTML</label><textarea id="article-body" name="body" aria-label="Article body HTML" data-tinymce-key="" rows="19">{escape(sample)}</textarea><div class="editor-bottom"><span>Use headings, short paragraphs, lists, and links to sources.</span><span id="word-count">0 words</span></div></section>
      <div class="studio-panel seo-preview"><div class="panel-head"><div><span class="admin-kicker">DISCOVERY</span><h2>Search preview</h2></div></div><span class="search-domain">financershub.com › personal-finance › emergency-fund</span><h3 id="search-preview-title">A clearer way to build an emergency fund</h3><p>A practical framework for choosing a target, setting a pace, and keeping cash available when you need it.</p></div></div>
      <aside class="editing-side"><div class="studio-panel side-module"><div class="module-head">Publishing <span>⌄</span></div><label class="admin-field"><span>Status</span><select><option>Draft</option><option>In review</option><option>Scheduled</option><option>Published</option></select></label>{field('Publish date','','datetime-local')}<div class="mini-info"><span>Storage</span><strong>This browser only</strong></div></div><div class="studio-panel side-module"><div class="module-head">Classification <span>⌄</span></div><label class="admin-field"><span>Primary category</span><select><option>Personal Finance</option><option>Investing</option><option>Banking</option><option>Credit</option></select></label>{field('Tags','Emergency fund, Saving')}</div><div class="studio-panel side-module"><div class="module-head">Featured media <span>⌄</span></div><img class="editor-media" src="/assets/images/editorial-personal-finance.webp" width="300" height="170" alt="Notebook and pen on a desk">{button('Change image','secondary','media')}<p class="small-muted">Confirm image rights and add meaningful alternative text where needed.</p></div><div class="studio-panel side-module"><div class="module-head">Editorial checks <span>⌄</span></div><label class="check-line"><input type="checkbox"> Primary sources checked</label><label class="check-line"><input type="checkbox"> Copy and image rights reviewed</label><label class="check-line"><input type="checkbox"> Disclaimer reviewed</label><label class="check-line"><input type="checkbox"> Second editorial review</label></div></aside></div>'''

def media():
    images=[('Editorial / Personal finance','editorial-personal-finance.webp'),('Editorial / Investing','editorial-investing.webp'),('Editorial / Banking','editorial-banking.webp')]
    cards=''.join(f'<button class="media-card" type="button" data-admin-action="select-media"><img src="/assets/images/{name}" alt="" width="420" height="260"><span>{label}<small>WebP · Editorial asset</small></span><b aria-hidden="true">⋯</b></button>' for label,name in images)
    return f'''<div class="list-toolbar"><div class="segmented"><button class="selected">All assets</button><button data-admin-action="filter-media">Images</button><button data-admin-action="filter-media">Documents</button></div>{button('＋ Upload media','primary','upload')}</div><div class="media-layout"><section><div class="media-drop"><span class="drop-icon">⇧</span><strong>Bring new assets into the library</strong><p>Upload, organize, and reuse approved visuals across the publication.</p>{button('Choose files','secondary','upload')}</div><div class="media-section-title"><h2>Recent assets</h2><span>3 sample images</span></div><div class="media-grid">{cards}</div></section><aside class="studio-panel media-guide"><span class="admin-kicker">ASSET GUIDELINES</span><h2>Make every image count.</h2><p>Use original visuals, descriptive filenames, sensible crops, and accurate alternative text.</p><div><strong>Recommended formats</strong><span>WebP · AVIF · SVG</span></div><div><strong>Hero ratio</strong><span>16:10 or 16:9</span></div><div><strong>Social image</strong><span>1200 × 630 px</span></div></aside></div>'''

def taxonomy(section, categories):
    if section=='categories':
        records=[(c,f'{c.lower().replace(" ","-")}',[18,14,12,10,9,8,7,6,5,4,3][i]) for i,c in enumerate(categories)]
        rows=''.join(f'<tr><td><strong>{n}</strong><small>Guides and explainers about {n.lower()}.</small></td><td class="mono">/{slug}</td><td>{count} articles</td><td>{badge("Visible","green")}</td><td>{button("Edit", "text", "edit")}</td></tr>' for n,slug,count in records)
        return f'''<div class="admin-two-col taxonomy-layout"><section class="studio-panel"><div class="panel-head"><div><span class="admin-kicker">SITE STRUCTURE</span><h2>Categories</h2></div>{button('＋ New category','primary','new-category')}</div><div class="table-scroll"><table class="studio-table"><thead><tr><th>Name</th><th>URL slug</th><th>Content</th><th>State</th><th></th></tr></thead><tbody>{rows}</tbody></table></div></section><aside class="studio-panel taxonomy-guide"><span class="admin-kicker">ORGANIZATION</span><h2>A useful path through the library.</h2><p>Categories shape main navigation and article breadcrumbs. Keep names distinct and reader-focused.</p><div class="guide-sample"><span>Example hierarchy</span><strong>Home <i>›</i> Investing <i>›</i> Article</strong></div></aside></div>'''
    tags=['Beginner guide','Explainer','Comparison','How-to','Credit basics','Risk','Cash flow','Financial planning','Review']
    return f'''<div class="admin-two-col taxonomy-layout"><section class="studio-panel"><div class="panel-head"><div><span class="admin-kicker">TOPIC CONNECTIONS</span><h2>Tags</h2></div>{button('＋ New tag','primary','new-tag')}</div><div class="tag-rows">{''.join(f'<div><span class="admin-tag">{t}</span><span>{(i*3+4)} articles</span>{button("Edit", "text", "edit")}</div>' for i,t in enumerate(tags))}</div></section><aside class="studio-panel taxonomy-guide"><span class="admin-kicker">EDITORIAL RULE</span><h2>Use tags with restraint.</h2><p>Tags should help readers find a meaningful connection. A category remains the main home for each article.</p></aside></div>'''

def authors():
    return '''<div class="list-toolbar"><span class="small-muted">Profiles shown here are placeholders for design review.</span><button class="a-button primary" type="button" data-admin-action="invite">＋ Add contributor</button></div><div class="author-grid"><article class="studio-panel author-card"><div class="author-avatar">FH</div><span class="status status-blue">Editorial team</span><h2>FinancersHub editorial team</h2><p>Shared sample attribution for the design preview. Replace with verified people and roles before launch.</p><div><span>Articles <strong>11</strong></span><span>Profile <strong>Needs verification</strong></span></div><button class="a-button secondary" type="button" data-admin-action="edit">Edit profile</button></article><article class="studio-panel author-invite"><span>＋</span><h2>Bring in a contributor</h2><p>Every writer profile should show a verified name, relevant experience, and a clear editorial role.</p><button class="a-button secondary" type="button" data-admin-action="invite">Create author profile</button></article></div>'''

def comments():
    notes=[('Jordan M.','This explanation helped me understand how to set my first milestone.','Emergency fund guide','Pending'),('A reader','Could you explain how this changes with variable income?','Saving and investing','Pending'),('Alex R.','The comparison table was especially useful.','Bank account guide','Approved')]
    return '<div class="list-toolbar"><div class="segmented"><button class="selected" data-comment-filter="all">All</button><button data-comment-filter="pending">Pending</button><button data-comment-filter="approved">Approved</button></div><span class="small-muted">Moderation actions are preview-only</span></div><div class="comment-layout"><section class="comment-list">'+''.join(f'<article class="studio-panel comment-card" data-comment-status="{status.lower()}"><div class="comment-top"><span class="comment-avatar">{name[0]}</span><div><strong>{name}</strong><small>On “{story}” · sample comment</small></div>{badge(status,"amber" if status=="Pending" else "green")}</div><p>{copy}</p><div class="comment-actions">{button("Approve","secondary","approve")} {button("Reply","secondary","reply")} {button("More ⋯","text","more")}</div></article>' for name,copy,story,status in notes)+'</section><aside class="studio-panel taxonomy-guide"><span class="admin-kicker">MODERATION PRINCIPLES</span><h2>Keep discussion useful.</h2><p>Review questions for relevance and civility. Do not treat reader comments as verified financial guidance.</p></aside></div>'

def seo():
    return f'''<div class="seo-layout"><div><section class="studio-panel"><div class="panel-head"><div><span class="admin-kicker">DEFAULTS</span><h2>Search appearance</h2></div>{badge('Preview','blue')}</div><div class="field-grid">{field('Site title','FinancersHub')}{field('Title suffix','| FinancersHub')}</div><label class="admin-field"><span>Default description</span><textarea rows="3">Clear explanations for real financial decisions.</textarea><small>Individual article metadata should override this description.</small></label></section><section class="studio-panel"><div class="panel-head"><div><span class="admin-kicker">SHARING</span><h2>Social preview</h2></div></div><div class="social-preview"><div class="social-cover"><img src="/assets/logo-white.svg" alt="FinancersHub" width="190" height="35"><span>FINANCE, EXPLAINED</span></div><div><strong>FinancersHub · Clear thinking about money</strong><span>financershub.com</span></div></div><p class="small-muted">The final social template needs article-specific titles and accessible text-safe crops.</p></section></div><aside class="studio-panel seo-checklist"><span class="admin-kicker">PUBLICATION CHECKLIST</span><h2>Search readiness</h2><div><span>✓</span><strong>Readable article structure</strong><small>One title and a logical heading order</small></div><div><span>✓</span><strong>Author attribution</strong><small>Visible near the article title</small></div><div><span>○</span><strong>Verified canonical URLs</strong><small>Connect when publishing routes exist</small></div><div><span>○</span><strong>Structured article data</strong><small>Add from verified content records</small></div>{button('Review settings','secondary','save')}</aside></div>'''

def advertisements():
    slots=[('Homepage leaderboard','Across content sections','Responsive · 970 × 90','Reserved'),('Article top','After article introduction','Responsive · 728 × 90','Reserved'),('Article middle','Within long-form content','Responsive · 728 × 90','Reserved'),('Article sidebar','Beside contextual reading','300 × 250','Reserved'),('Mobile in-feed','Between story groups','320 × 100','Reserved')]
    cards=''.join(f'<article class="slot-card"><div class="slot-preview"><span>ADVERTISEMENT</span><small>{size}</small></div><div class="slot-details"><span>{badge(state,"blue")}</span><h3>{name}</h3><p>{where}</p>{button("Placement details", "text", "slot")}</div></article>' for name,where,size,state in slots)
    return f'''<div class="admin-two-col ads-layout"><section><div class="list-toolbar"><p class="small-muted">Slots reserve space to protect the reading experience.</p>{button('＋ New placement','primary','new-slot')}</div><div class="slot-grid">{cards}</div></section><aside class="studio-panel ad-guidelines"><span class="admin-kicker">AD PRINCIPLES</span><h2>Revenue without disruption.</h2><p>All ad placements are visibly labeled and have predictable dimensions. This screen is an inventory; no ad network is connected.</p><ul><li>Reserve the expected slot height</li><li>Keep ads separate from editorial cards</li><li>Use fewer slots on narrow screens</li></ul></aside></div>'''

def faq():
    rows=''.join(f'<article class="faq-edit-item"><label class="admin-field"><span>Question</span><input class="faq-question" value="{escape(q,quote=True)}" required></label><label class="admin-field"><span>Answer</span><textarea class="faq-answer-edit" rows="4" required>{escape(answer)}</textarea></label><button type="button" class="a-button secondary faq-remove">Remove question</button></article>' for _,group in FAQ_GROUPS for q,answer in group)
    return f'''<div class="admin-two-col faq-admin-layout"><section class="studio-panel"><div class="panel-head"><div><span class="admin-kicker">READER HELP</span><h2>Frequently asked questions</h2></div><a href="/faq.html" target="_blank" rel="noopener">View current page ↗</a></div><p class="small-muted">Edit a draft of the FAQ text here. Saving keeps it in this browser; changes will appear on the public page after a CMS is connected and published.</p><form id="faq-admin-form"><div id="faq-edit-list">{rows}</div><div class="faq-admin-actions"><button type="button" id="faq-add" class="a-button secondary">＋ Add question</button><button type="submit" class="a-button primary">Save draft in this browser</button></div><p id="faq-admin-status" role="status"></p></form></section><aside class="studio-panel taxonomy-guide"><span class="admin-kicker">WRITING NOTES</span><h2>Give readers a direct answer.</h2><p>Use one question per topic, plain language, and links to the full policy or guide when readers need detail.</p><p>Do not promise newsletter delivery or personalized advice before those services are available.</p></aside></div>'''

def newsletter():
    return '''<div class="admin-metrics three"><div><span>Subscribers</span><strong>—</strong><small>No signup service connected</small><i>✉</i></div><div><span>Campaigns</span><strong>—</strong><small>Delivery not connected</small><i>✎</i></div><div><span>Signup placement</span><strong>01</strong><small>Above the footer</small><i>▧</i></div></div><div class="newsletter-workflow"><section class="studio-panel"><div class="panel-head"><div><span class="admin-kicker">SIGNUP COPY</span><h2>Newsletter invitation</h2></div><a href="/#newsletter" target="_blank" rel="noopener">View current placement ↗</a></div><p class="small-muted">Draft copy for the pre-footer signup. Save it in this browser for review; connect an email provider and publishing backend before collecting addresses.</p><form id="newsletter-admin-form"><label class="admin-field"><span>Title</span><input id="newsletter-title-edit" value="Good questions for better money decisions."></label><label class="admin-field"><span>Description</span><textarea id="newsletter-description-edit" rows="3">A short selection of practical guides, delivered when the newsletter launches.</textarea></label><label class="admin-field"><span>Button label</span><input id="newsletter-button-edit" value="Get updates"></label><div class="setting-actions"><button class="a-button primary" type="submit">Save draft in this browser</button></div><p id="newsletter-admin-status" role="status"></p></form></section><aside class="studio-panel signup-preview"><span class="admin-kicker">READER EXPERIENCE</span><h2>One useful idea at a time.</h2><p>State what readers will receive, how often, and how to unsubscribe when email delivery is ready.</p><div class="signup-mock"><span>Email address</span><strong>Get updates ↗</strong></div><small>The public form is a preview and does not collect addresses.</small><a href="/faq.html#newsletter-and-contact">Read the newsletter FAQ ↗</a></aside></div>'''

def settings():
    return f'''<div class="settings-layout"><nav class="settings-nav" aria-label="Settings sections"><a href="#identity" class="selected">Site identity</a><a href="#navigation">Navigation</a><a href="#appearance">Appearance</a><a href="#integrations">Integrations</a></nav><div><section id="identity" class="studio-panel"><div class="panel-head"><div><span class="admin-kicker">PUBLICATION</span><h2>Site identity</h2></div></div><div class="field-grid">{field('Publication name','FinancersHub')}{field('Public site URL','financershub.com')}</div><label class="admin-field"><span>Short description</span><textarea rows="3">Clear explanations for real financial decisions.</textarea></label><div class="setting-actions">{button('Save changes','primary','save')}</div></section><section id="navigation" class="studio-panel"><div class="panel-head"><div><span class="admin-kicker">WAYFINDING</span><h2>Main navigation</h2></div></div><div class="nav-order">{''.join(f'<div><span>⠿</span><strong>{item}</strong><span>Visible</span></div>' for item in ['Personal Finance','Investing','Banking','Credit','Business','Saving'])}</div></section><section id="appearance" class="studio-panel"><div class="panel-head"><div><span class="admin-kicker">BRAND</span><h2>Appearance</h2></div></div><div class="brand-swatches"><span style="background:#132c43"></span><span style="background:#137b71"></span><span style="background:#edf3f1"></span><strong>Navy / teal editorial system</strong></div></section><section id="integrations" class="studio-panel"><div class="panel-head"><div><span class="admin-kicker">FUTURE CONNECTIONS</span><h2>Integrations</h2></div></div><p class="small-muted">Advertising, newsletter delivery, analytics, and content storage will be connected in a later phase.</p></section></div></div>'''

def render_admin(section, articles, categories):
    pages={'index':lambda:overview(articles),'articles':lambda:article_list(articles),'editor':editor,'media':media,'categories':lambda:taxonomy('categories',categories),'tags':lambda:taxonomy('tags',categories),'authors':authors,'comments':comments,'faq':faq,'seo':seo,'advertisements':advertisements,'newsletter':newsletter,'settings':settings}
    return shell(section,pages[section]())
