@extends('layouts.studio')
@section('live','1')
@section('title','Maintenance console')
@section('content')
<div class="studio-heading"><div><span class="admin-kicker">SYSTEM OPERATIONS</span><h1>Maintenance console</h1><p>Inspect the application, refresh caches and keep a clear record of every task.</p></div><span class="status-pill neutral">Admin access only</span></div>
<div class="console-summary"><div><span>Recorded runs</span><strong>{{ $totalRuns }}</strong></div><div><span>Needs attention</span><strong>{{ $attentionRuns }}</strong></div><div><span>Configuration cache</span><strong>{{ app()->configurationIsCached() ? 'Cached' : 'Live' }}</strong></div><div><span>Route cache</span><strong>{{ app()->routesAreCached() ? 'Cached' : 'Live' }}</strong></div></div>
<div class="console-layout"><section class="studio-panel"><div class="record-list-heading"><h2>Choose a task</h2><span class="meta">{{ count($commands) }} reviewed commands</span></div>
<div class="console-task-list">@foreach($commands as $command=>$label)<button type="button" class="console-task {{ $selected===$command ? 'selected' : '' }}" data-command="{{ $command }}" data-description="{{ $descriptions[$command] }}" aria-pressed="{{ $selected===$command ? 'true' : 'false' }}"><span>{{ $label }}</span><code>{{ $command }}</code></button>@endforeach</div></section>
<section class="studio-panel console-runner"><span class="admin-kicker">TASK RUNNER</span><h2>Ready when you are</h2><form method="post" action="{{ route('admin.maintenance.run') }}" data-busy-label="Running task...">@csrf
<label class="admin-field">Selected command<select name="command" id="maintenance-command">@foreach($commands as $command=>$label)<option value="{{ $command }}" data-description="{{ $descriptions[$command] }}" @selected($selected===$command)>{{ $command }}</option>@endforeach</select></label>
<p class="console-task-description" id="task-description">{{ $descriptions[$selected] }}</p>
<label class="admin-field">Confirm your password<input name="password" type="password" autocomplete="current-password" required><small>Your password is checked for this run and never stored in task history.</small></label>
<label class="check-line"><input type="checkbox" name="confirm_migration" value="1"><span>For migrations: I have a current database backup and approve applying pending migrations.</span></label><button class="a-button primary" type="submit">Run selected task &rarr;</button></form><div class="console-note"><strong>Controlled application maintenance</strong><p>Only the tasks listed here can run. Migrations require explicit backup confirmation. Destructive resets, interactive commands, shell access and long-running workers require a deployment terminal.</p></div></section></div>
<section class="studio-panel"><div class="record-list-heading"><h2>Execution history</h2><span class="meta">All times UTC</span></div><form method="get" class="admin-toolbar compact-toolbar"><label class="admin-field">Command<select name="command"><option value="">All commands</option>@foreach($commands as $command=>$label)<option value="{{ $command }}" @selected(request('command')===$command)>{{ $command }}</option>@endforeach</select></label><label class="admin-field">Outcome<select name="outcome"><option value="">All outcomes</option><option value="success" @selected(request('outcome')==='success')>Successful</option><option value="attention" @selected(request('outcome')==='attention')>Needs attention</option></select></label><div class="toolbar-actions"><button class="a-button secondary">Filter history</button><a href="{{ route('admin.maintenance') }}">Reset</a></div></form>
@forelse($runs as $run)<details class="console-history" @if($loop->first) open @endif><summary><div><code>{{ $run->command }}</code><small>{{ $run->created_at }} &middot; {{ $run->actor_name ?? 'Former staff member' }}</small></div><span class="status-pill {{ $run->exit_code === 0 ? 'success' : 'warning' }}">{{ is_null($run->exit_code) ? 'Running / interrupted' : ($run->exit_code === 0 ? 'Completed' : 'Needs attention') }}</span></summary><div class="console-output-bar"><span>Run #{{ $run->id }} &middot; Exit code {{ $run->exit_code ?? 'pending' }}</span><button type="button" class="a-button secondary compact" data-copy-output="run-output-{{ $run->id }}">Copy output</button></div><pre class="maintenance-output" id="run-output-{{ $run->id }}">{{ $run->output ?: 'No output was recorded.' }}</pre></details>
@empty<div class="admin-empty"><h3>No runs to display</h3><p>Run a task above or change your history filters.</p></div>@endforelse
{{ $runs->links('pagination.simple') }}</section>
<details class="studio-panel command-catalog"><summary>All installed Artisan commands</summary><p>Browser-ready tasks appear in the picker above. Other commands require terminal access, arguments or lifecycle controls and cannot run through a web request.</p><label class="admin-field">Find a command<input type="search" id="command-search" placeholder="Search name or description"></label><div class="studio-table-wrap"><table class="admin-table"><thead><tr><th>Command</th><th>Description</th><th>Execution</th></tr></thead><tbody>@foreach($catalog as $entry)<tr data-catalog-command><td><code>{{ $entry['name'] }}</code></td><td>{{ $entry['description'] }}</td><td>{{ $entry['runnable'] ? 'Browser ready' : 'Terminal only' }}</td></tr>@endforeach</tbody></table></div></details>
@endsection
