@extends('layouts.studio')
@section('section','editor')
@section('title','Write article')
@section('intro','Build a clear, well-structured finance guide.')
@section('content')
<div class="editor-status"><div><x-status-badge tone="blue">Draft</x-status-badge><span id="draft-state">Browser-local draft preview · no CMS connected</span></div><div><button class="a-button secondary" type="button" data-admin-action="preview">Preview</button><button class="a-button primary" type="button" data-admin-action="save">Save to this browser</button><button class="a-button dark" type="button" data-admin-action="publish">Publish ▾</button></div></div>
<div class="editing-layout">
  <div class="editing-main">
    <section class="studio-panel story-setup"><span class="admin-kicker">THE STORY</span><label class="admin-field"><span>Headline</span><input class="headline-input" id="editor-title" value="{{ $article['title'] ?? '' }}" placeholder="Enter a descriptive headline"></label><label class="admin-field"><span>Short description</span><textarea id="editor-summary" rows="2" placeholder="Summarize the article">{{ $article['excerpt'] ?? '' }}</textarea><small>A concise summary for listings and search results.</small></label></section>
    <section class="studio-panel editor-panel"><div class="editor-panel-top"><span class="admin-kicker">ARTICLE BODY</span><span id="editor-mode">TinyMCE setup</span></div>
      <div class="tinymce-setup" id="tinymce-setup"><div><strong>Write with TinyMCE</strong><p>Enter your Tiny Cloud API key to activate the visual editor. The key is kept in this browser for this preview. Add this Site’s domain to your approved domains in Tiny Cloud.</p></div><label class="sr-only" for="tinymce-key">Tiny Cloud API key</label><div class="tinymce-key-row"><input id="tinymce-key" type="password" autocomplete="off" placeholder="Your Tiny Cloud API key"><button class="a-button primary" id="activate-tinymce" type="button">Activate editor</button><button class="a-button secondary" id="forget-tinymce-key" type="button">Forget key</button></div><p id="tinymce-status" role="status">No API key is configured. You can still edit the HTML below.</p></div>
      <label class="sr-only" for="article-body">Article body HTML</label><textarea id="article-body" name="body" aria-label="Article body HTML" data-tinymce-key="{{ config('financershub.tinymce_api_key', '') }}" rows="19">{{ $article['sanitized_editor_html'] ?? '<p>Start writing your guide here.</p>' }}</textarea><div class="editor-bottom"><span>Use headings, short paragraphs, lists, and links to sources.</span><span id="word-count">0 words</span></div></section>
    <section class="studio-panel seo-preview"><div class="panel-head"><div><span class="admin-kicker">DISCOVERY</span><h2>Search preview</h2></div></div><span class="search-domain">financershub.com › article</span><h3 id="search-preview-title">{{ $article['title'] ?? 'Untitled article' }}</h3><p>{{ $article['excerpt'] ?? '' }}</p></section>
  </div>
  <aside class="editing-side"><section class="studio-panel side-module"><div class="module-head">Publishing <span>⌄</span></div><label class="admin-field"><span>Status</span><select><option>Draft</option><option>In review</option><option>Scheduled</option><option>Published</option></select></label><label class="admin-field"><span>Publish date</span><input type="datetime-local"></label></section><section class="studio-panel side-module"><div class="module-head">Classification <span>⌄</span></div><label class="admin-field"><span>Primary category</span><select>@foreach($categories as $category)<option>{{ $category['name'] }}</option>@endforeach</select></label><label class="admin-field"><span>Tags</span><input value="{{ implode(', ', $article['tags'] ?? []) }}"></label></section><section class="studio-panel side-module"><div class="module-head">Editorial checks <span>⌄</span></div><label class="check-line"><input type="checkbox"> Primary sources checked</label><label class="check-line"><input type="checkbox"> Copy and image rights reviewed</label><label class="check-line"><input type="checkbox"> Disclaimer reviewed</label><label class="check-line"><input type="checkbox"> Second editorial review</label></section></aside>
</div>
@endsection
