<footer class="footer"><div class="wrap">
  <section class="footer-newsletter" id="newsletter" aria-labelledby="newsletter-title"><div class="footer-newsletter-copy"><span class="footer-kicker">THE FINANCERSHUB BRIEF</span><h2 id="newsletter-title">Good questions for<br><em>better money decisions.</em></h2><p>A short selection of practical guides, delivered when the newsletter launches.</p></div><div class="footer-newsletter-action"><form data-demo-form class="footer-signup"><label for="footer-email">Email address</label><div><input id="footer-email" name="email" type="email" autocomplete="email" placeholder="you@example.com" required><button type="submit">Get updates <span aria-hidden="true">↗</span></button></div></form><p class="signup-honesty">Signup is coming soon. This preview does not collect your email. <a href="{{ url('/faq') }}#newsletter-and-contact">How it will work</a></p></div></section>
  <div class="footer-grid">
    <div class="footer-brand"><a class="logo" href="{{ url('/') }}"><img src="{{ asset('assets/logo-white.svg') }}" width="323" height="62" alt="FinancersHub"></a><p>Useful questions. Clear explanations. Room to make up your own mind.</p><a class="footer-library-link" href="{{ url('/search') }}">Explore the full guide library ↗</a></div>
    <nav aria-label="Explore topics"><h3>Explore</h3>@foreach (['Personal Finance','Investing','Banking','Credit','Business'] as $section)<a href="{{ url('/categories/'.\Illuminate\Support\Str::slug($section)) }}">{{ $section }}</a>@endforeach<a href="{{ url('/search') }}">All articles</a></nav>
    <nav aria-label="Publication links"><h3>The publication</h3><a href="{{ url('/about') }}">About us</a><a href="{{ url('/editorial-policy') }}">Editorial policy</a><a href="{{ url('/authors/editorial-team') }}">Authors</a><a href="{{ url('/faq') }}">FAQs</a><a href="{{ url('/contact') }}">Contact</a></nav>
    <nav aria-label="Information links"><h3>Information</h3><a href="{{ url('/disclaimer') }}">Financial disclaimer</a><a href="{{ url('/privacy') }}">Privacy</a><a href="{{ url('/terms') }}">Terms of use</a></nav>
  </div>
  <div class="footer-bottom"><span>© {{ date('Y') }} FinancersHub</span><span>Educational content only. Not personalized financial, investment, tax, or legal advice.</span><a href="#top">Back to top ↑</a></div>
</div></footer>
