@extends('layouts.site')
@section('title','Contact | FinancersHub')
@section('description','Contact FinancersHub about an article, correction, or editorial suggestion.')
@push('styles')<link rel="stylesheet" href="{{ asset('assets/info.css') }}">@endpush
@section('content')
<div class="wrap contact-page"><x-breadcrumbs :items="[['label'=>'Contact']]" />
  <header class="contact-hero"><div><span class="eyebrow">CONTACT FINANCERSHUB</span><h1>Start a useful<br><em>conversation.</em></h1><p>Ask about a guide, flag a correction, or tell us what you would like us to explain next.</p></div><div class="contact-hero-note"><span class="eyebrow">THE RIGHT PLACE TO START</span><p>For article corrections, include the page link and the detail that needs a second look. For general feedback, a short description is enough.</p></div></header>
  <div class="contact-preview-note" role="note"><span aria-hidden="true">ⓘ</span><p><strong>Design preview.</strong> This form demonstrates the contact experience; messages are not delivered yet.</p></div>
  <div class="contact-layout"><div class="contact-form-card"><div class="form-card-heading"><span class="eyebrow">YOUR MESSAGE</span><h2>What would you like to share?</h2><p>Fields marked <span aria-hidden="true">*</span> are required.</p></div>
    <form class="contact-form" data-demo-form><div class="contact-field-row"><label><span class="field-label">Your name <span aria-hidden="true">*</span></span><input name="name" autocomplete="name" required placeholder="Full name"></label><label><span class="field-label">Email address <span aria-hidden="true">*</span></span><input type="email" name="email" autocomplete="email" required placeholder="you@example.com"></label></div>
      <label><span class="field-label">What is this about? <span aria-hidden="true">*</span></span><select name="subject" required><option value="" disabled selected>Choose a subject</option><option>Question about an article</option><option>Correction or update</option><option>Topic suggestion</option><option>General inquiry</option></select></label>
      <label><span class="field-label">Related article link <small>Optional</small></span><input type="url" name="article" inputmode="url" placeholder="https://..."><small class="field-help">A direct link helps us identify the page you mean.</small></label>
      <label><span class="field-label">Your message <span aria-hidden="true">*</span></span><textarea name="message" rows="7" required placeholder="Tell us what you would like us to know..."></textarea></label><div class="contact-submit"><p>Please do not include account numbers, passwords, or other sensitive financial details.</p><button class="btn" type="submit">Preview form <span aria-hidden="true">↗</span></button></div>
    </form>
  </div><aside class="contact-aside"><div class="contact-side-intro"><span class="eyebrow">BEFORE YOU WRITE</span><h2>Help us understand the context.</h2><p>A clear question or a specific page link makes feedback easier to review.</p></div><div><span class="info-number">01 / QUESTIONS</span><h3>Ask about an article</h3><p>Share the guide and the part you want clarified.</p></div><div><span class="info-number">02 / CORRECTIONS</span><h3>Flag a detail</h3><p>Include the page link, the detail in question, and a source if you have one.</p></div><div><span class="info-number">03 / SUGGESTIONS</span><h3>Suggest a topic</h3><p>Tell us the money decision you would like a guide to cover.</p></div><div class="contact-aside-note"><span class="eyebrow">LEARN MORE</span><p>See how we intend to review and update content.</p><a href="{{ url('/editorial-policy') }}">Our editorial approach ↗</a></div></aside></div>
</div>
@endsection
