@extends('layouts.site')
@section('title', 'FinancersHub | Understand money. Move with confidence.')
@section('content')
<section class="wrap opening"><div class="opening-copy"><span class="eyebrow">THE FINANCERSHUB EDIT</span><h1>Understand money.<br><em>Move with confidence.</em></h1><p>Thoughtful guides on personal finance, investing, banking and the choices that shape your financial life.</p></div></section>
<section class="wrap front-grid" aria-label="Featured stories">
  <article class="front-lead"><a class="lead-image" href="{{ url('/articles/'.$featured['slug']) }}"><img src="{{ asset($featured['image'] ?? 'assets/images/editorial-personal-finance.webp') }}" width="1600" height="1000" alt="{{ $featured['image_alt'] ?? '' }}" fetchpriority="high"></a><div class="lead-copy"><span class="eyebrow">THE LEAD / {{ strtoupper($featured['category']) }}</span><h2><a href="{{ url('/articles/'.$featured['slug']) }}">{{ $featured['title'] }}</a></h2><p>{{ $featured['excerpt'] }}</p><a class="text-link" href="{{ url('/articles/'.$featured['slug']) }}">Read the guide ↗</a></div></article>
  <div class="front-rail"><div class="rail-heading"><span class="eyebrow">ALSO IN FOCUS</span><span class="meta">02—03</span></div>@foreach($secondary as $item)<article class="lead-secondary"><a href="{{ url('/articles/'.$item['slug']) }}"><div class="art"><img src="{{ asset($item['image'] ?? 'assets/images/editorial-investing.webp') }}" width="800" height="500" alt="" loading="lazy"></div></a><div><span class="eyebrow">{{ $item['category'] }}</span><h3><a href="{{ url('/articles/'.$item['slug']) }}">{{ $item['title'] }}</a></h3><span class="meta">{{ $item['read_time'] ?? 'Guide' }}</span></div></article>@endforeach</div>
</section>
<section class="wrap section editorial-section"><div class="section-head"><div><span class="eyebrow">EXPLORE THE GUIDES</span><h2>Guides from the desk</h2></div><a class="text-link" href="{{ url('/search') }}">The full library ↗</a></div><div class="card-grid">@foreach($latest as $item)<x-article-card :article="$item" />@endforeach</div></section>
@foreach(($guideShelves ?? []) as $shelf)
<section class="wrap home-shelf" aria-labelledby="shelf-{{ $loop->iteration }}"><div class="shelf-heading"><div><span class="eyebrow">READER PATH</span><h2 id="shelf-{{ $loop->iteration }}">{{ $shelf['title'] }}</h2></div><a class="text-link" href="{{ url('/search') }}">Explore the library ↗</a></div><div class="shelf-cards">@foreach($shelf['articles'] as $item)<x-article-card :article="$item" />@endforeach</div></section>
@endforeach
<section class="topic-band"><div class="wrap"><div class="section-head"><div><span class="eyebrow">EXPLORE THE LIBRARY</span><h2>Find your starting point.</h2></div></div><div class="topic-grid">@foreach($categories as $category)<a class="topic-tile" href="{{ url('/categories/'.$category['slug']) }}"><span class="topic-number">{{ sprintf('%02d',$loop->iteration) }}</span><strong>{{ $category['name'] }}</strong><span class="topic-arrow">↗</span></a>@endforeach</div></div></section>
<section class="wrap library-strip"><div><span class="eyebrow">THE FINANCERSHUB LIBRARY</span><h2>Find a guide for the question on your mind.</h2></div><a class="text-link" href="{{ url('/search') }}">Browse all guides ↗</a></section>
@endsection
