@extends('layouts.studio')
@section('title', 'Editor')
@section('content')
<div class="studio-heading"><div><span class="admin-kicker">EDITORIAL STUDIO / EDITOR</span><h1>Write article</h1><p>Build a clear, well-structured finance guide.</p></div></div><div class="editor-status"><div><span class="status status-blue">Draft</span><span id="draft-state">Design preview · no CMS connected</span></div><div><button disabled title="Not connected in design preview" class="a-button secondary" type="button" data-admin-action="preview">Preview</button> <button disabled title="Not connected in design preview" class="a-button primary" type="button" data-admin-action="save">Save draft (unavailable)</button> <button disabled title="Not connected in design preview" class="a-button dark" type="button" data-admin-action="publish">Publish ▾</button></div></div>
      <div class="editing-layout"><div class="editing-main"><div class="studio-panel story-setup"><span class="admin-kicker">THE STORY</span><label class="admin-field"><span>Headline <em>*</em></span><input class="headline-input" id="editor-title" value="A clearer way to build an emergency fund" aria-label="Article headline"></label><label class="admin-field"><span>Short description</span><textarea id="editor-summary" rows="2">A practical framework for choosing a target, setting a pace, and keeping cash available when you need it.</textarea><small>A concise summary for listings and search results.</small></label></div>
      <section class="studio-panel editor-panel"><div class="editor-panel-top"><span class="admin-kicker">ARTICLE BODY</span><span id="editor-mode">TinyMCE setup</span></div><div class="tinymce-setup" id="tinymce-setup"><strong>Article editor</strong><p id="tinymce-status" role="status">Configure TINYMCE_API_KEY in the environment to enable the visual editor. The HTML textarea remains available.</p></div><label class="sr-only" for="article-body">Article body HTML</label><textarea id="article-body" name="body" aria-label="Article body HTML" data-tinymce-key="{{ config('financershub.tinymce_api_key') }}" rows="19">&lt;h2&gt;Start with the decision&lt;/h2&gt;&lt;p&gt;Explain what the reader is trying to decide, then show the costs, limits, and questions that matter.&lt;/p&gt;&lt;h2&gt;What to check&lt;/h2&gt;&lt;ul&gt;&lt;li&gt;Use current primary sources.&lt;/li&gt;&lt;li&gt;Show trade-offs and uncertainties.&lt;/li&gt;&lt;li&gt;Provide a practical next step.&lt;/li&gt;&lt;/ul&gt;</textarea><div class="editor-bottom"><span>Use headings, short paragraphs, lists, and links to sources.</span><span id="word-count">0 words</span></div></section>
      <div class="studio-panel seo-preview"><div class="panel-head"><div><span class="admin-kicker">DISCOVERY</span><h2>Search preview</h2></div></div><span class="search-domain">financershub.com › personal-finance › emergency-fund</span><h3 id="search-preview-title">A clearer way to build an emergency fund</h3><p>A practical framework for choosing a target, setting a pace, and keeping cash available when you need it.</p></div></div>
      <aside class="editing-side"><div class="studio-panel side-module"><div class="module-head">Publishing <span>⌄</span></div><label class="admin-field"><span>Status</span><select><option>Draft</option><option>In review</option><option>Scheduled</option><option>Published</option></select></label><label class="admin-field"><span>Publish date</span><input type="datetime-local" value="" placeholder=""></label><div class="mini-info"><span>Storage</span><strong>Not connected</strong></div></div><div class="studio-panel side-module"><div class="module-head">Classification <span>⌄</span></div><label class="admin-field"><span>Primary category</span><select><option>Personal Finance</option><option>Investing</option><option>Banking</option><option>Credit</option></select></label><label class="admin-field"><span>Tags</span><input type="text" value="Emergency fund, Saving" placeholder=""></label></div><div class="studio-panel side-module"><div class="module-head">Featured media <span>⌄</span></div><img class="editor-media" src="{{ asset('assets/images/editorial-personal-finance.webp') }}" width="300" height="170" alt="Notebook and pen on a desk"><button disabled title="Not connected in design preview" class="a-button secondary" type="button" data-admin-action="media">Change image</button><p class="small-muted">Confirm image rights and add meaningful alternative text where needed.</p></div><div class="studio-panel side-module"><div class="module-head">Editorial checks <span>⌄</span></div><label class="check-line"><input type="checkbox"> Primary sources checked</label><label class="check-line"><input type="checkbox"> Copy and image rights reviewed</label><label class="check-line"><input type="checkbox"> Disclaimer reviewed</label><label class="check-line"><input type="checkbox"> Second editorial review</label></div></aside></div>
@endsection
